workspace = { members = ["days/aoc23_day01"] }
[package]
name = "rust-advent-of-code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

